---
title: "Combining LSS and LDA"
author: "KoheiWatanabe"
date: "13/12/2018"
output: rmarkdown::html_vignette
---

```{r, echo=FALSE}
knitr::opts_chunk$set(
  collapse = FALSE,
  comment = "##",
  fig.path = "images/",
  fig.height = 5,
  fig.width = 10
)
```

```{r, message=FALSE}
require(quanteda)
require(LSS)
require(topicmodels)
```

```{r}
corp <- readRDS('/home/kohei/Dropbox/Public/data_corpus_guardian2016-10k.rds')
```


### Fit a LDA model

```{r, cache=TRUE}
toks <- corp %>% 
    tokens(remove_punct = TRUE)
mt <- toks %>% 
    dfm(remove = stopwords()) %>% 
    dfm_select('^[a-zA-Z]+$', valuetype = 'regex') %>% 
    dfm_trim(min_termfreq = 0.95, termfreq_type = "quantile", 
             max_docfreq = 0.1, docfreq_type = "prop")

lda <- LDA(convert(mt[ntoken(mt) > 0,], to = "topicmodels"), 10, 
           control = list(seed = 1234))
print(terms(lda, 10))
```



### Fit a LSS model

```{r, cache=TRUE}
toks_sent <- corp %>% 
    corpus_reshape('sentences') %>% 
    tokens(remove_punct = TRUE)
mt_sent <- toks_sent %>% 
    dfm(remove = stopwords()) %>% 
    dfm_select('^[a-zA-Z]+$', valuetype = 'regex') %>% 
    dfm_trim(min_termfreq = 5)

eco <- terms(lda, 500)[,10]
pol <- terms(lda, 500)[,7]

#' sentiment model on economy
lss_eco <- textmodel_lss(mt_sent, seedwords('pos-neg'), features = eco)

# sentiment model on politics
lss_pol <- textmodel_lss(mt_sent, seedwords('pos-neg'), features = pol)

```


### Sentiment seed words

Seed words are 14 generic sentiment words.

```{r}
seedwords('pos-neg')
```

### Sentiment words

LSS identifies domain specific words and weight them by sentiment.

#### Economic words

```{r}
head(coef(lss_eco), 20) # most positive words
tail(coef(lss_eco), 20) # most negative words

```

#### Political words

```{r}
head(coef(lss_pol), 20) # most positive words
tail(coef(lss_pol), 20) # most negative words
```

## Predict sentiment of news

```{r}
mt <- dfm(toks)
```

### Economic sentiment

```{r}
pred_eco <- as.data.frame(predict(lss_eco, newdata = mt, density = TRUE))
pred_eco$date <- docvars(mt, 'date')
pred_eco <- na.omit(pred_eco)

plot(pred_eco$date, pred_eco$fit, pch = 16, col = rgb(0, 0, 0, 0.1),
     ylim = c(-1, 1), ylab = 'economic sentiment')
lines(lowess(pred_eco$date, pred_eco$fit, f = 0.05), col = 1)
abline(h = 0, v = as.Date("2016-06-23"), lty = c(1, 3))
```


### Political sentiment

```{r}
pred_pol <- as.data.frame(predict(lss_pol, newdata = mt, density = TRUE))
pred_pol$date <- docvars(mt, 'date')
pred_pol <- na.omit(pred_pol)

plot(pred_pol$date, pred_pol$fit, pch = 16, col = rgb(1, 0, 0, 0.1),
     ylim = c(-1, 1), ylab = 'political sentiment')
lines(lowess(pred_pol$date, pred_pol$fit, f = 0.05), col = 2)
abline(h = 0, v = as.Date("2016-06-23"), lty = c(1, 3))
```

### Comparison

```{r}
plot(docvars(mt, 'date'), rep(0, ndoc(mt)), type = 'n',
     ylim = c(-0.5, 0.5), ylab = 'economic/political sentiment')
grid()
lines(lowess(pred_eco$date, pred_eco$fit, f = 0.05), col = 1)
lines(lowess(pred_pol$date, pred_pol$fit, f = 0.05), col = 2)
abline(h = 0)
legend('topright', lty = 1, col = 1:2, legend = c('political', 'economic'))
abline(h = 0, v = as.Date("2016-06-23"), lty = c(1, 3))
```


