// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// flag_collocates_cppl
Rcpp::List flag_collocates_cppl(List texts, const Rcpp::CharacterVector& targets, const int& window, const int& n);
RcppExport SEXP LSS_flag_collocates_cppl(SEXP textsSEXP, SEXP targetsSEXP, SEXP windowSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type texts(textsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type targets(targetsSEXP);
    Rcpp::traits::input_parameter< const int& >::type window(windowSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(flag_collocates_cppl(texts, targets, window, n));
    return rcpp_result_gen;
END_RCPP
}
