# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_colflag_cpp <- function(indices, window, len) {
    .Call('LSS_get_colflag_cpp', PACKAGE = 'LSS', indices, window, len)
}

select_tokens_cppl <- function(x, types, remove, spacer) {
    .Call('LSS_select_tokens_cppl', PACKAGE = 'LSS', x, types, remove, spacer)
}

