# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

flag_window_cpp <- function(centers, window, len, flag_center) {
    .Call('LSS_flag_window_cpp', PACKAGE = 'LSS', centers, window, len, flag_center)
}

