# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

flag_window_cpp <- function(centers, window, len, flag_center) {
    .Call('LSS_flag_window_cpp', PACKAGE = 'LSS', centers, window, len, flag_center)
}

select_tokens_cppl <- function(x, types, remove, spacer) {
    .Call('LSS_select_tokens_cppl', PACKAGE = 'LSS', x, types, remove, spacer)
}

